#!/usr/bin/env python3

# import your main class here, and run your handler in main()

"""
Ex:
from app.utils import RedditBotBase


class Bot(RedditBotBase):
    def main():
        while True:
            print(f"...some bot is running")
            for post in self.reddit.subreddit(self.subreddit).stream.submissions(pause_after=1):
                # some loop code here

            time.sleep(self.delay)


def main():
    b = Bot()
    b.main()
"""
def main():
    pass


if __name__ == "__main__":
    main()
